// Code generated by the lightning generator from event.go; DO NOT EDIT.

package example

import (
	"github.com/JohanLindvall/lightning/pkg/unstable"
)

func (v *Event) UnmarshalJSON(data []byte) error {
	i := unstable.SkipWS(data, 0)
	if uint(i) >= uint(len(data)) {
		return unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return err
		}
		if unstable.SkipWS(data, end) != len(data) {
			return unstable.ErrInvalidJSON
		}
		return nil
	}
	end, err := lightningGithubComJohanLindvallLightningExampleEventdecodeEvent(v, data, i)
	if err != nil {
		return err
	}
	if unstable.SkipWS(data, end) != len(data) {
		return unstable.ErrInvalidJSON
	}
	return nil
}

func lightningGithubComJohanLindvallLightningExampleEventdecodeStringSlice(out *[]string, data []byte, i int) (int, error) {
	if uint(i) >= uint(len(data)) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return end, err
		}
		*out = nil
		return end, nil
	}
	if data[i] != '[' {
		return i, unstable.ErrExpectArray
	}
	if len(*out) != 0 {
		*out = (*out)[:0]
	}
	if *out == nil {
		if n := unstable.CountArrayElements(data, i); n > 0 {
			*out = make([]string, 0, n)
		}
	}
	i++
	for first := true; ; first = false {
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) {
			return i, unstable.ErrTruncated
		}
		if data[i] == ']' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var zero string
		*out = append(*out, zero)
		s, end, err := unstable.ReadStringOrNull(data, i)
		if err != nil {
			return end, err
		}
		(*out)[len(*out)-1] = s
		i = end
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) {
			return i, unstable.ErrTruncated
		}
		if data[i] == ']' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallLightningExampleEventdecodeEvent(v *Event, data []byte, i int) (int, error) {
	if uint(i) >= uint(len(data)) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if uint(i) >= uint(len(data)) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if ke := unstable.IndexCloseOrEscapeAt(data, ks); uint(ke) < uint(len(data)) && data[ke] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ke]), ke+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "id":
			n, end, err := unstable.ReadInt64OrNull(data, i)
			if err != nil {
				return end, err
			}
			v.ID = n
			i = end
		case "kind":
			s, end, err := unstable.ReadStringOrNull(data, i)
			if err != nil {
				return end, err
			}
			v.Kind = s
			i = end
		case "at":
			t, end, err := unstable.ReadTimeOrNull(data, i)
			if err != nil {
				return end, err
			}
			v.At = t
			i = end
		case "tags":
			end, err := lightningGithubComJohanLindvallLightningExampleEventdecodeStringSlice(&v.Tags, data, i)
			if err != nil {
				return end, err
			}
			i = end

		default:
			var end int
			var err error
			switch lightningC := data[i]; {
			case lightningC >= '[':
				end, err = unstable.SkipValue(data, i)
			case lightningC == '"':
				end, err = unstable.SkipString(data, i)
			default:
				end, err = unstable.SkipNumber(data, i)
			}
			if err != nil {
				return end, err
			}
			i = end
		}
		if uint(i) < uint(len(data)) && data[i] <= ' ' {
			i++
			if uint(i) < uint(len(data)) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if uint(i) >= uint(len(data)) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}
