// Code generated from github_events.json (minio/simdjson-go testdata); root renamed Benchmark.
package bench

type Benchmark []struct {
	Actor struct {
		AvatarUrl  string `json:"avatar_url"`
		GravatarId string `json:"gravatar_id"`
		ID         int64  `json:"id"`
		Login      string `json:"login"`
		URL        string `json:"url"`
	} `json:"actor"`
	CreatedAt string `json:"created_at"`
	ID        string `json:"id"`
	Payload   struct {
		Before  string `json:"before"`
		Commits []struct {
			Author struct {
				Email string `json:"email"`
				Name  string `json:"name"`
			} `json:"author"`
			Distinct bool   `json:"distinct"`
			Message  string `json:"message"`
			Sha      string `json:"sha"`
			URL      string `json:"url"`
		} `json:"commits"`
		DistinctSize int64  `json:"distinct_size"`
		Head         string `json:"head"`
		PushId       int64  `json:"push_id"`
		Ref          any    `json:"ref"`
		Size         int64  `json:"size"`
		Description  string `json:"description"`
		MasterBranch string `json:"master_branch"`
		RefType      string `json:"ref_type"`
		Forkee       struct {
			ArchiveUrl       string `json:"archive_url"`
			AssigneesUrl     string `json:"assignees_url"`
			BlobsUrl         string `json:"blobs_url"`
			BranchesUrl      string `json:"branches_url"`
			CloneUrl         string `json:"clone_url"`
			CollaboratorsUrl string `json:"collaborators_url"`
			CommentsUrl      string `json:"comments_url"`
			CommitsUrl       string `json:"commits_url"`
			CompareUrl       string `json:"compare_url"`
			ContentsUrl      string `json:"contents_url"`
			ContributorsUrl  string `json:"contributors_url"`
			CreatedAt        string `json:"created_at"`
			Description      string `json:"description"`
			DownloadsUrl     string `json:"downloads_url"`
			EventsUrl        string `json:"events_url"`
			Fork             bool   `json:"fork"`
			Forks            int64  `json:"forks"`
			ForksCount       int64  `json:"forks_count"`
			ForksUrl         string `json:"forks_url"`
			FullName         string `json:"full_name"`
			GitCommitsUrl    string `json:"git_commits_url"`
			GitRefsUrl       string `json:"git_refs_url"`
			GitTagsUrl       string `json:"git_tags_url"`
			GitUrl           string `json:"git_url"`
			HasDownloads     bool   `json:"has_downloads"`
			HasIssues        bool   `json:"has_issues"`
			HasWiki          bool   `json:"has_wiki"`
			Homepage         any    `json:"homepage"`
			HooksUrl         string `json:"hooks_url"`
			HtmlUrl          string `json:"html_url"`
			ID               int64  `json:"id"`
			IssueCommentUrl  string `json:"issue_comment_url"`
			IssueEventsUrl   string `json:"issue_events_url"`
			IssuesUrl        string `json:"issues_url"`
			KeysUrl          string `json:"keys_url"`
			LabelsUrl        string `json:"labels_url"`
			Language         string `json:"language"`
			LanguagesUrl     string `json:"languages_url"`
			MergesUrl        string `json:"merges_url"`
			MilestonesUrl    string `json:"milestones_url"`
			MirrorUrl        any    `json:"mirror_url"`
			Name             string `json:"name"`
			NotificationsUrl string `json:"notifications_url"`
			OpenIssues       int64  `json:"open_issues"`
			OpenIssuesCount  int64  `json:"open_issues_count"`
			Owner            struct {
				AvatarUrl         string `json:"avatar_url"`
				EventsUrl         string `json:"events_url"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				GravatarId        string `json:"gravatar_id"`
				ID                int64  `json:"id"`
				Login             string `json:"login"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				ReposUrl          string `json:"repos_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				Type              string `json:"type"`
				URL               string `json:"url"`
			} `json:"owner"`
			Private         bool   `json:"private"`
			Public          bool   `json:"public"`
			PullsUrl        string `json:"pulls_url"`
			PushedAt        string `json:"pushed_at"`
			Size            int64  `json:"size"`
			SshUrl          string `json:"ssh_url"`
			StargazersUrl   string `json:"stargazers_url"`
			StatusesUrl     string `json:"statuses_url"`
			SubscribersUrl  string `json:"subscribers_url"`
			SubscriptionUrl string `json:"subscription_url"`
			SvnUrl          string `json:"svn_url"`
			TagsUrl         string `json:"tags_url"`
			TeamsUrl        string `json:"teams_url"`
			TreesUrl        string `json:"trees_url"`
			UpdatedAt       string `json:"updated_at"`
			URL             string `json:"url"`
			Watchers        int64  `json:"watchers"`
			WatchersCount   int64  `json:"watchers_count"`
		} `json:"forkee"`
		Action  string `json:"action"`
		Comment struct {
			Body      string `json:"body"`
			CreatedAt string `json:"created_at"`
			ID        int64  `json:"id"`
			IssueUrl  string `json:"issue_url"`
			UpdatedAt string `json:"updated_at"`
			URL       string `json:"url"`
			User      struct {
				AvatarUrl         string `json:"avatar_url"`
				EventsUrl         string `json:"events_url"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				GravatarId        string `json:"gravatar_id"`
				ID                int64  `json:"id"`
				Login             string `json:"login"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				ReposUrl          string `json:"repos_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				Type              string `json:"type"`
				URL               string `json:"url"`
			} `json:"user"`
		} `json:"comment"`
		Issue struct {
			Assignee    any    `json:"assignee"`
			Body        string `json:"body"`
			ClosedAt    any    `json:"closed_at"`
			Comments    int64  `json:"comments"`
			CommentsUrl string `json:"comments_url"`
			CreatedAt   string `json:"created_at"`
			EventsUrl   string `json:"events_url"`
			HtmlUrl     string `json:"html_url"`
			ID          int64  `json:"id"`
			Labels      []any  `json:"labels"`
			LabelsUrl   string `json:"labels_url"`
			Milestone   any    `json:"milestone"`
			Number      int64  `json:"number"`
			PullRequest struct {
				DiffUrl  any `json:"diff_url"`
				HtmlUrl  any `json:"html_url"`
				PatchUrl any `json:"patch_url"`
			} `json:"pull_request"`
			State     string `json:"state"`
			Title     string `json:"title"`
			UpdatedAt string `json:"updated_at"`
			URL       string `json:"url"`
			User      struct {
				AvatarUrl         string `json:"avatar_url"`
				EventsUrl         string `json:"events_url"`
				FollowersUrl      string `json:"followers_url"`
				FollowingUrl      string `json:"following_url"`
				GistsUrl          string `json:"gists_url"`
				GravatarId        string `json:"gravatar_id"`
				ID                int64  `json:"id"`
				Login             string `json:"login"`
				OrganizationsUrl  string `json:"organizations_url"`
				ReceivedEventsUrl string `json:"received_events_url"`
				ReposUrl          string `json:"repos_url"`
				StarredUrl        string `json:"starred_url"`
				SubscriptionsUrl  string `json:"subscriptions_url"`
				Type              string `json:"type"`
				URL               string `json:"url"`
			} `json:"user"`
		} `json:"issue"`
		Pages []struct {
			Action   string `json:"action"`
			HtmlUrl  string `json:"html_url"`
			PageName string `json:"page_name"`
			Sha      string `json:"sha"`
			Summary  any    `json:"summary"`
			Title    string `json:"title"`
		} `json:"pages"`
	} `json:"payload"`
	Public bool `json:"public"`
	Repo   struct {
		ID   int64  `json:"id"`
		Name string `json:"name"`
		URL  string `json:"url"`
	} `json:"repo"`
	Type string `json:"type"`
	Org  struct {
		AvatarUrl  string `json:"avatar_url"`
		GravatarId string `json:"gravatar_id"`
		ID         int64  `json:"id"`
		Login      string `json:"login"`
		URL        string `json:"url"`
	} `json:"org"`
}
